### PR TITLE
multi-thread make

### PR DESCRIPTION
**Pull request by tomjtoth**
please check the 2nd `make` command as I'm not familiar with those flags.

### CODE REVIEW

**Comment by tomjtoth** [comment]
took 3 minutes on a `Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz`, you might want to check for free memory, I ended up killing firefox to free up another ~8GB ^^

**Comment by qzuw** [comment]
- When compiling, extra free memory is never disadvantage, and too little memory can indeed cause significant slowdowns.
- 5 minutes was meant as intentional overestimate, to account for variable hardware and network speeds (iirc, using lab computers it took about 3 minutes or so at the time). It is mentioned only to give very rough indication of the time required. (Amusingly enough, computer I'm currently using to write this, with my current programs open, compilation seems to be fairly accurately 5 min.)
- It seems that adding -j would require defining extra requirements, by changelogs -j might not be in oldest makes Postgres mentions as requirement.
- nproc is unnecessary: man make says "If the  -j  option  is given without an argument, make will not limit the number of jobs that can run simultaneously."

IMO, few minutes is not really that big difference, for action you possibly do once, or at worst once for coding session. As it is now, script follows fairly closely instructions in Postgres documentation, meaning less maintenance.

Leaving open for other opinions, though I definitely would like to see nproc removed from pr if it were to be merged.

**Comment by qzuw** [comment]
Oh, and make install-strip is just installation target action for make, it's defined in Makefiles generated by configure. -j probably doesn't help there much or at all.

**Comment by qzuw** [comment]
Added variable to enable make -j, though it is disabled by default. No documentation changes since it is not enabled by default.

Closing as PR does not currently apply and functionality is now available.

Feel free to comment if you test it.

**Pull request closed without merging**
